name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, ubuntu-20.04, ubuntu-22.04]


    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
           sudo apt install pkg-config libjavascriptcoregtk-4.0-dev
         fi
      shell: bash
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
